### ISSUE TITLE
Reading outside the email client

### ISSUE THREAD

**Issue by nilbus** [codedevotional/community#1]
Thanks for putting this together! I haven't read through the first article yet, but I am looking forward to it.

Lots of emails these days have a _view this email in your browser_ link, with an http link to the email content. I ❤️ those links for longer content because, like any other web content, I can throw it in [Pocket][] to read later. Even better, the Pocket mobile app reads the email to me, and with a pretty decent voice. I ingest most of my online reading in this format. Being busy, it's much harder to find time to sit down and read than it is to find time to listen, which I can do during other tasks—driving, cleaning, etc. I can technically make my phone read an email to me, but it's much more awkward and doesn't fit in with the normal flow of how I read other content. I imagine the same is true for others who have some system for collecting online reading material. The email client isn't the best place for that, IMO.

[Pocket]: https://getpocket.com/

If it's not a terrible amount of trouble, could you arrange for your email content to be hosted on the web and linked to from the email? Thanks!

**Comment by tjstankus** [comment]
Thanks for your feedback @nilbus and thanks for posting the first issue!

This content *will* be posted on the Code Devotional blog. It's sent to email list subscribers first primarily as a thank you for subscribing. One concern I have about posting a public web link before the blog article is that it would likely be shared via social media, etc. Then, eventually, there are two public versions out there, one of which we don't control for purposes of editing, etc.

We'll continue to think through this and collect feedback - thanks again!

**Comment by nilbus** [comment]
Ah, I see your concern. I don't know whether unpublished articles are supported on your blog which might allow direct linking only. If so, perhaps you could achieve having both a single web version and early availability to email subscribers. If people read, enjoy, and share it early on social media, that sounds like a good thing to me. When the blog post is published publicly later, it won't often be on email subscribers' minds any more for sharing.

**Comment by tjstankus** [comment]
@nilbus going forward, we're going to publish the blog post at the same time as the mailing, so this should not be an issue. Thanks again for your feeback!
